# Generated by Django 4.2.2 on 2023-06-28 20:56

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Employee',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('employee_creation_date', models.DateTimeField(auto_now_add=True, verbose_name='User creation date')),
                ('employee_last_modified', models.DateTimeField(auto_now_add=True, verbose_name='Last modified on')),
                ('employee_first_name', models.CharField(max_length=30, verbose_name='First name')),
                ('employee_last_name', models.CharField(max_length=30, verbose_name='Last name')),
                ('employee_seniority', models.CharField(choices=[('Intern', 'Intern'), ('Junior', 'Junior'), ('Regular', 'Regular'), ('Senior', 'Senior')], max_length=30, verbose_name='Seniority')),
                ('employee_position', models.CharField(choices=[('Customer Service Rep', 'Customer Service Representative'), ('Tech Support Rep', 'Technical Support Representative'), ('Sales Rep', 'Sales Representative'), ('COR', 'Contracting Officer Representative'), ('Dev', 'Developer'), ('QA', 'Quality Assurance'), ('DevOps', 'Development and Operations Representative'), ('SysAdmin', 'System Administrator'), ('System Architect', 'System Architect'), ('Team Leader', 'Team Leader'), ('COO', 'Chief Operations Officer'), ('CSO', 'Chief Sales Officer'), ('CTO', 'Chief Technology Officer '), ('CPO', 'Chief Procurement Officer'), ('CEO', 'Chief Executive Officer')], max_length=30, verbose_name='Position')),
                ('employee_email_address', models.EmailField(max_length=254, unique=True, verbose_name='Email address')),
                ('employee_contract_type', models.CharField(choices=[('Temporary', 'Temporary'), ('Permanent', 'Permanent')], verbose_name='Contract type')),
            ],
        ),
    ]
