# Generated by Django 4.2.2 on 2023-06-28 22:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Employees', '0003_rename_department_name_employee_employee_department_name_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='employee',
            name='employee_projects_involvement',
        ),
    ]
