# Generated by Django 4.2.2 on 2023-07-09 10:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Employees', '0004_remove_employee_employee_projects_involvement'),
    ]

    operations = [
        migrations.AlterField(
            model_name='employee',
            name='employee_email_address',
            field=models.EmailField(blank=True, max_length=254, null=True, unique=True, verbose_name='Email address'),
        ),
    ]
