# Generated by Django 4.2.2 on 2023-07-11 18:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Employees', '0005_alter_employee_employee_email_address'),
    ]

    operations = [
        migrations.AddField(
            model_name='employee',
            name='employee_photo',
            field=models.ImageField(blank=True, null=True, upload_to='', verbose_name='Employee photo'),
        ),
    ]
