# Generated by Django 4.2.2 on 2023-07-16 19:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Employees', '0007_employeephoto'),
    ]

    operations = [
        migrations.AddField(
            model_name='employee',
            name='employee_user_admin_access',
            field=models.BooleanField(blank=True, default=False),
        ),
        migrations.AddField(
            model_name='employee',
            name='employee_user_is_admin',
            field=models.BooleanField(default=False),
        ),
    ]
