# Generated by Django 4.2.2 on 2023-07-16 19:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Employees', '0008_employee_employee_user_admin_access_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='employee',
            name='employee_user_admin_access',
            field=models.BooleanField(choices=[(True, 'Yes'), (False, 'No')], default=False),
        ),
        migrations.AlterField(
            model_name='employee',
            name='employee_user_is_admin',
            field=models.BooleanField(choices=[(True, 'Yes'), (False, 'No')], default=False),
        ),
    ]
