# Generated by Django 4.2.2 on 2023-07-16 20:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Employees', '0009_alter_employee_employee_user_admin_access_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='employee',
            name='employee_contract_type',
            field=models.CharField(choices=[('Trial period', 'Trial period'), ('Temporary', 'Temporary'), ('Permanent', 'Permanent'), ('Terminated', 'Terminated')], verbose_name='Contract type'),
        ),
    ]
