# Generated by Django 4.2.2 on 2023-07-17 11:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Employees', '0010_alter_employee_employee_contract_type'),
    ]

    operations = [
        migrations.AlterField(
            model_name='employee',
            name='employee_photo',
            field=models.ImageField(blank=True, null=True, upload_to='employee_user_photos', verbose_name='Employee photo'),
        ),
    ]
