# Generated by Django 4.2.2 on 2023-07-17 11:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Employees', '0011_alter_employee_employee_photo'),
    ]

    operations = [
        migrations.AddField(
            model_name='employee',
            name='employee_user_personal_id',
            field=models.CharField(default=123456, max_length=6),
            preserve_default=False,
        ),
    ]
