# Generated by Django 4.2.2 on 2023-07-17 11:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Employees', '0013_remove_employee_employee_user_personal_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='employee',
            name='employee_user_personal_id',
            field=models.CharField(blank=True, default=None, max_length=6, null=True),
        ),
    ]
