# Generated by Django 4.2.2 on 2023-07-17 15:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Employees', '0015_alter_employee_employee_user_personal_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='employee',
            name='employee_slug',
            field=models.SlugField(null=True, unique=True),
        ),
    ]
