# Generated by Django 4.2.2 on 2023-07-18 14:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Employees', '0019_remove_employee_employee_slug'),
    ]

    operations = [
        migrations.AddField(
            model_name='employee',
            name='slug',
            field=models.SlugField(null=True, unique=True),
        ),
    ]
