# Generated by Django 4.2.2 on 2023-07-18 13:14

from django.db import migrations
from django.utils.text import slugify


def add_slugs(apps, schema_editor):
    Employee = apps.get_model("Employees", "Employee")

    all_employees = Employee.objects.all()

    for employee in all_employees:
        employee_full_name = f'{employee.employee_first_name} {employee.employee_last_name}'
        employee.slug = slugify(employee_full_name)

    Employee.objects.bulk_update(all_employees, fields=['slug', ])


def delete_slugs(apps, schema_editor):
    Employee = apps.get_model("Employees", "Employee")

    all_employees = Employee.objects.all()

    for employee in all_employees:
        employee.slug = None

    Employee.objects.bulk_update(all_employees, fields=['slug', ])





class Migration(migrations.Migration):

    dependencies = [
        ('Employees', '0020_employee_slug'),
    ]

    operations = [
        migrations.RunPython(add_slugs, delete_slugs)
    ]
