# Generated by Django 4.2.2 on 2023-07-18 14:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Employees', '0021_fill_slug_for_existing_employee'),
    ]

    operations = [
        migrations.AlterField(
            model_name='employee',
            name='slug',
            field=models.SlugField(default=None, unique=True),
        ),
    ]
