# Generated by Django 4.2.2 on 2023-07-22 12:23

import Project_04_Models_Part_2.Employees.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Employees', '0024_alter_employee_employee_photo'),
    ]

    operations = [
        migrations.AlterField(
            model_name='employee',
            name='employee_photo',
            field=models.ImageField(blank=True, null=True, upload_to=Project_04_Models_Part_2.Employees.models.get_upload_path, verbose_name='Employee photo'),
        ),
    ]
