# Generated by Django 4.2.2 on 2023-06-28 20:56

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Project',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('project_creation_date', models.DateTimeField(auto_now_add=True, verbose_name='Department creation date')),
                ('project_last_modified', models.DateTimeField(auto_now_add=True, verbose_name='Last modified on')),
                ('project_name', models.CharField(max_length=100, unique=True, verbose_name='Department name')),
                ('project_email_address', models.EmailField(max_length=254, unique=True, verbose_name='Email address')),
                ('project_development_start_date', models.DateTimeField(auto_now=True, verbose_name='Project Development Start Date')),
                ('project_development_completion_deadline_date', models.DateTimeField(auto_now=True, verbose_name='Project Development Completion Deadline Date')),
                ('project_status', models.CharField(choices=[('N/A', 'N/A'), ('Planing', 'Planing'), ('Development', 'Development'), ('Deployment', 'Deployment'), ('Termination', 'Termination')], max_length=20, verbose_name='Project Status')),
                ('project_deployment_start_date', models.DateTimeField(auto_now=True, verbose_name='Project Development Start Date')),
            ],
        ),
    ]
