# Generated by Django 4.2.2 on 2023-06-28 21:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Projects', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='project',
            name='project_name',
            field=models.CharField(max_length=100, unique=True, verbose_name='Project name'),
        ),
    ]
