# Generated by Django 4.2.2 on 2023-06-28 22:21

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Departments', '0003_remove_department_department_projects'),
        ('Employees', '0004_remove_employee_employee_projects_involvement'),
        ('Projects', '0002_alter_project_project_name'),
    ]

    operations = [
        migrations.CreateModel(
            name='ProjectAppointmentDepartmentsAndEmployees',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('current_project_name', models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, to='Projects.project')),
                ('project_appointed_departments', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='Departments.department')),
                ('project_appointed_employees', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='Employees.employee')),
            ],
        ),
        migrations.AddField(
            model_name='project',
            name='project_departments_appointed',
            field=models.ManyToManyField(through='Projects.ProjectAppointmentDepartmentsAndEmployees', to='Departments.department'),
        ),
        migrations.AddField(
            model_name='project',
            name='project_employees_appointed',
            field=models.ManyToManyField(through='Projects.ProjectAppointmentDepartmentsAndEmployees', to='Employees.employee'),
        ),
    ]
