# Generated by Django 4.2.2 on 2023-06-28 22:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Departments', '0003_remove_department_department_projects'),
        ('Employees', '0004_remove_employee_employee_projects_involvement'),
        ('Projects', '0003_projectappointmentdepartmentsandemployees_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='project',
            name='project_departments_appointed',
        ),
        migrations.RemoveField(
            model_name='project',
            name='project_employees_appointed',
        ),
        migrations.RemoveField(
            model_name='projectappointmentdepartmentsandemployees',
            name='project_appointed_departments',
        ),
        migrations.RemoveField(
            model_name='projectappointmentdepartmentsandemployees',
            name='project_appointed_employees',
        ),
        migrations.AddField(
            model_name='projectappointmentdepartmentsandemployees',
            name='project_appointed_departments',
            field=models.ManyToManyField(to='Departments.department'),
        ),
        migrations.AddField(
            model_name='projectappointmentdepartmentsandemployees',
            name='project_appointed_employees',
            field=models.ManyToManyField(to='Employees.employee'),
        ),
    ]
