# Generated by Django 4.2.2 on 2023-06-19 20:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Models', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='employee',
            name='employed_permanently',
            field=models.BooleanField(blank=True, choices=[('True', 'True'), ('False', 'False')], verbose_name='Employed permanently'),
        ),
    ]
