# Generated by Django 4.2.2 on 2023-06-19 20:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Models', '0003_alter_employee_employed_on_probation'),
    ]

    operations = [
        migrations.AlterField(
            model_name='employee',
            name='employed_full_time',
            field=models.BooleanField(blank=True, choices=[('True', 'True'), ('False', 'False')], verbose_name='Employed full time'),
        ),
    ]
