# Generated by Django 4.2.2 on 2023-06-19 20:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Models', '0004_alter_employee_employed_full_time'),
    ]

    operations = [
        migrations.AlterField(
            model_name='employee',
            name='employed_on_probation',
            field=models.BooleanField(blank=True, choices=[('True', 'True'), ('False', 'False')], null=True, verbose_name='On probation'),
        ),
    ]
