# Generated by Django 4.2.2 on 2023-06-19 21:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Models', '0011_rename_employee_project_employees_appointment_test_employee_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='test_department',
            name='test_department_email_address',
            field=models.EmailField(max_length=254, verbose_name='TEST_Department email address'),
        ),
        migrations.AlterField(
            model_name='test_department',
            name='test_department_employees_id',
            field=models.CharField(max_length=10, unique=True, verbose_name='TEST_Employee ID'),
        ),
        migrations.AlterField(
            model_name='test_department',
            name='test_department_id',
            field=models.CharField(max_length=10, unique=True, verbose_name='TEST_Department ID'),
        ),
        migrations.AlterField(
            model_name='test_department',
            name='test_department_name',
            field=models.CharField(max_length=30, unique=True, verbose_name='TEST_Department name'),
        ),
        migrations.AlterField(
            model_name='test_department',
            name='test_department_project_id',
            field=models.CharField(max_length=300, verbose_name='TEST_Involved in Projects'),
        ),
        migrations.AlterField(
            model_name='test_project',
            name='test_project_department_id',
            field=models.CharField(blank=True, max_length=300, verbose_name='TEST_Departments involved'),
        ),
        migrations.AlterField(
            model_name='test_project',
            name='test_project_employees_id',
            field=models.CharField(blank=True, max_length=300, verbose_name='TEST_Employees involved'),
        ),
        migrations.AlterField(
            model_name='test_project',
            name='test_project_id',
            field=models.CharField(blank=True, max_length=10, unique=True, verbose_name='TEST_Project ID'),
        ),
        migrations.AlterField(
            model_name='test_project',
            name='test_project_name',
            field=models.CharField(max_length=30, unique=True, verbose_name='TEST_Project name'),
        ),
    ]
