
all_countries_names = [
    'Afghanistan',
    'Albania',
    'Algeria',
    'Andorra',
    'Angola',
    'Antigua and Barbuda',
    'Argentina',
    'Armenia',
    'Australia',
    'Austria',
    'Azerbaijan',
    'The Bahamas',
    'Bahrain',
    'Bangladesh',
    'Barbados',
    'Belarus',
    'Belgium',
    'Belize',
    'Benin',
    'Bhutan',
    'Bolivia',
    'Bosnia and Herzegovina',
    'Botswana',
    'Brazil',
    'Brunei',
    'Bulgaria',
    'Burkina Faso',
    'Burundi',
    'Cabo Verde',
    'Cambodia',
    'Cameroon',
    'Canada',
    'Central African Republic',
    'Chad',
    'Chile',
    'China',
    'Colombia',
    'Comoros',
    'Congo, Democratic Republic of the',
    'Congo, Republic of the',
    'Costa Rica',
    'Côte d’Ivoire',
    'Croatia',
    'Cuba',
    'Cyprus',
    'Czech Republic',
    'Denmark',
    'Djibouti',
    'Dominica',
    'Dominican Republic',
    'East Timor (Timor-Leste)',
    'Ecuador',
    'Egypt',
    'El Salvador',
    'Equatorial Guinea',
    'Eritrea',
    'Estonia',
    'Eswatini',
    'Ethiopia',
    'Fiji',
    'Finland',
    'France',
    'Gabon',
    'The Gambia',
    'Georgia',
    'Germany',
    'Ghana',
    'Greece',
    'Grenada',
    'Guatemala',
    'Guinea',
    'Guinea-Bissau',
    'Guyana',
    'Haiti',
    'Honduras',
    'Hungary',
    'Iceland',
    'India',
    'Indonesia',
    'Iran',
    'Iraq',
    'Ireland',
    'Israel',
    'Italy',
    'Jamaica',
    'Japan',
    'Jordan',
    'Kazakhstan',
    'Kenya',
    'Kiribati',
    'Korea, North',
    'Korea, South',
    'Kosovo',
    'Kuwait',
    'Kyrgyzstan',
    'Laos',
    'Latvia',
    'Lebanon',
    'Lesotho',
    'Liberia',
    'Libya',
    'Liechtenstein',
    'Lithuania',
    'Luxembourg',
    'Madagascar',
    'Malawi',
    'Malaysia',
    'Maldives',
    'Mali',
    'Malta',
    'Marshall Islands',
    'Mauritania',
    'Mauritius',
    'Mexico',
    'Micronesia, Federated States of',
    'Moldova',
    'Monaco',
    'Mongolia',
    'Montenegro',
    'Morocco',
    'Mozambique',
    'Myanmar (Burma)',
    'Namibia',
    'Nauru',
    'Nepal',
    'Netherlands',
    'New Zealand',
    'Nicaragua',
    'Niger',
    'Nigeria',
    'North Macedonia',
    'Norway',
    'Oman',
    'Pakistan',
    'Palau',
    'Panama',
    'Papua New Guinea',
    'Paraguay',
    'Peru',
    'Philippines',
    'Poland',
    'Portugal',
    'Qatar',
    'Romania',
    'Russia',
    'Rwanda',
    'Saint Kitts and Nevis',
    'Saint Lucia',
    'Saint Vincent and the Grenadines',
    'Samoa',
    'San Marino',
    'Sao Tome and Principe',
    'Saudi Arabia',
    'Senegal',
    'Serbia',
    'Seychelles',
    'Sierra Leone',
    'Singapore',
    'Slovakia',
    'Slovenia',
    'Solomon Islands',
    'Somalia',
    'South Africa',
    'Spain',
    'Sri Lanka',
    'Sudan',
    'Sudan, South',
    'Suriname',
    'Sweden',
    'Switzerland',
    'Syria',
    'Taiwan',
    'Tajikistan',
    'Tanzania',
    'Thailand',
    'Togo',
    'Tonga',
    'Trinidad and Tobago',
    'Tunisia',
    'Turkey',
    'Turkmenistan',
    'Tuvalu',
    'Uganda',
    'Ukraine',
    'United Arab Emirates',
    'United Kingdom',
    'United States',
    'Uruguay',
    'Uzbekistan',
    'Vanuatu',
    'Vatican City',
    'Venezuela',
    'Vietnam',
    'Yemen',
    'Zambia'
]

all_countries_choices_fields_format = (
    ('afghanistan', 'Afghanistan'),
    ('albania', 'Albania'),
    ('algeria', 'Algeria'),
    ('andorra', 'Andorra'),
    ('angola', 'Angola'),
    ('antigua and barbuda', 'Antigua and barbuda'),
    ('argentina', 'Argentina'),
    ('armenia', 'Armenia'),
    ('australia', 'Australia'),
    ('austria', 'Austria'),
    ('azerbaijan', 'Azerbaijan'),
    ('the bahamas', 'The bahamas'),
    ('bahrain', 'Bahrain'),
    ('bangladesh', 'Bangladesh'),
    ('barbados', 'Barbados'),
    ('belarus', 'Belarus'),
    ('belgium', 'Belgium'),
    ('belize', 'Belize'),
    ('benin', 'Benin'),
    ('bhutan', 'Bhutan'),
    ('bolivia', 'Bolivia'),
    ('bosnia and herzegovina', 'Bosnia and herzegovina'),
    ('botswana', 'Botswana'),
    ('brazil', 'Brazil'),
    ('brunei', 'Brunei'),
    ('bulgaria', 'Bulgaria'),
    ('burkina faso', 'Burkina faso'),
    ('burundi', 'Burundi'),
    ('cabo verde', 'Cabo verde'),
    ('cambodia', 'Cambodia'),
    ('cameroon', 'Cameroon'),
    ('canada', 'Canada'),
    ('central african republic', 'Central african republic'),
    ('chad', 'Chad'),
    ('chile', 'Chile'),
    ('china', 'China'),
    ('colombia', 'Colombia'),
    ('comoros', 'Comoros'),
    ('congo, democratic republic of the', 'Congo, democratic republic of the'),
    ('congo, republic of the', 'Congo, republic of the'),
    ('costa rica', 'Costa rica'),
    ('côte d’ivoire', 'Côte d’ivoire'),
    ('croatia', 'Croatia'),
    ('cuba', 'Cuba'),
    ('cyprus', 'Cyprus'),
    ('czech republic', 'Czech republic'),
    ('denmark', 'Denmark'),
    ('djibouti', 'Djibouti'),
    ('dominica', 'Dominica'),
    ('dominican republic', 'Dominican republic'),
    ('east timor (timor-leste)', 'East timor (timor-leste)'),
    ('ecuador', 'Ecuador'),
    ('egypt', 'Egypt'),
    ('el salvador', 'El salvador'),
    ('equatorial guinea', 'Equatorial guinea'),
    ('eritrea', 'Eritrea'),
    ('estonia', 'Estonia'),
    ('eswatini', 'Eswatini'),
    ('ethiopia', 'Ethiopia'),
    ('fiji', 'Fiji'),
    ('finland', 'Finland'),
    ('france', 'France'),
    ('gabon', 'Gabon'),
    ('the gambia', 'The gambia'),
    ('georgia', 'Georgia'),
    ('germany', 'Germany'),
    ('ghana', 'Ghana'),
    ('greece', 'Greece'),
    ('grenada', 'Grenada'),
    ('guatemala', 'Guatemala'),
    ('guinea', 'Guinea'),
    ('guinea-bissau', 'Guinea-bissau'),
    ('guyana', 'Guyana'),
    ('haiti', 'Haiti'),
    ('honduras', 'Honduras'),
    ('hungary', 'Hungary'),
    ('iceland', 'Iceland'),
    ('india', 'India'),
    ('indonesia', 'Indonesia'),
    ('iran', 'Iran'),
    ('iraq', 'Iraq'),
    ('ireland', 'Ireland'),
    ('israel', 'Israel'),
    ('italy', 'Italy'),
    ('jamaica', 'Jamaica'),
    ('japan', 'Japan'),
    ('jordan', 'Jordan'),
    ('kazakhstan', 'Kazakhstan'),
    ('kenya', 'Kenya'),
    ('kiribati', 'Kiribati'),
    ('korea, north', 'Korea, north'),
    ('korea, south', 'Korea, south'),
    ('kosovo', 'Kosovo'),
    ('kuwait', 'Kuwait'),
    ('kyrgyzstan', 'Kyrgyzstan'),
    ('laos', 'Laos'),
    ('latvia', 'Latvia'),
    ('lebanon', 'Lebanon'),
    ('lesotho', 'Lesotho'),
    ('liberia', 'Liberia'),
    ('libya', 'Libya'),
    ('liechtenstein', 'Liechtenstein'),
    ('lithuania', 'Lithuania'),
    ('luxembourg', 'Luxembourg'),
    ('madagascar', 'Madagascar'),
    ('malawi', 'Malawi'),
    ('malaysia', 'Malaysia'),
    ('maldives', 'Maldives'),
    ('mali', 'Mali'),
    ('malta', 'Malta'),
    ('marshall islands', 'Marshall islands'),
    ('mauritania', 'Mauritania'),
    ('mauritius', 'Mauritius'),
    ('mexico', 'Mexico'),
    ('micronesia, federated states of', 'Micronesia, federated states of'),
    ('moldova', 'Moldova'),
    ('monaco', 'Monaco'),
    ('mongolia', 'Mongolia'),
    ('montenegro', 'Montenegro'),
    ('morocco', 'Morocco'),
    ('mozambique', 'Mozambique'),
    ('myanmar (burma)', 'Myanmar (burma)'),
    ('namibia', 'Namibia'),
    ('nauru', 'Nauru'),
    ('nepal', 'Nepal'),
    ('netherlands', 'Netherlands'),
    ('new zealand', 'New zealand'),
    ('nicaragua', 'Nicaragua'),
    ('niger', 'Niger'),
    ('nigeria', 'Nigeria'),
    ('north macedonia', 'North macedonia'),
    ('norway', 'Norway'),
    ('oman', 'Oman'),
    ('pakistan', 'Pakistan'),
    ('palau', 'Palau'),
    ('panama', 'Panama'),
    ('papua new guinea', 'Papua new guinea'),
    ('paraguay', 'Paraguay'),
    ('peru', 'Peru'),
    ('philippines', 'Philippines'),
    ('poland', 'Poland'),
    ('portugal', 'Portugal'),
    ('qatar', 'Qatar'),
    ('romania', 'Romania'),
    ('russia', 'Russia'),
    ('rwanda', 'Rwanda'),
    ('saint kitts and nevis', 'Saint kitts and nevis'),
    ('saint lucia', 'Saint lucia'),
    ('saint vincent and the grenadines', 'Saint vincent and the grenadines'),
    ('samoa', 'Samoa'),
    ('san marino', 'San marino'),
    ('sao tome and principe', 'Sao tome and principe'),
    ('saudi arabia', 'Saudi arabia'),
    ('senegal', 'Senegal'),
    ('serbia', 'Serbia'),
    ('seychelles', 'Seychelles'),
    ('sierra leone', 'Sierra leone'),
    ('singapore', 'Singapore'),
    ('slovakia', 'Slovakia'),
    ('slovenia', 'Slovenia'),
    ('solomon islands', 'Solomon islands'),
    ('somalia', 'Somalia'),
    ('south africa', 'South africa'),
    ('spain', 'Spain'),
    ('sri lanka', 'Sri lanka'),
    ('sudan', 'Sudan'),
    ('sudan, south', 'Sudan, south'),
    ('suriname', 'Suriname'),
    ('sweden', 'Sweden'),
    ('switzerland', 'Switzerland'),
    ('syria', 'Syria'),
    ('taiwan', 'Taiwan'),
    ('tajikistan', 'Tajikistan'),
    ('tanzania', 'Tanzania'),
    ('thailand', 'Thailand'),
    ('togo', 'Togo'),
    ('tonga', 'Tonga'),
    ('trinidad and tobago', 'Trinidad and tobago'),
    ('tunisia', 'Tunisia'),
    ('turkey', 'Turkey'),
    ('turkmenistan', 'Turkmenistan'),
    ('tuvalu', 'Tuvalu'),
    ('uganda', 'Uganda'),
    ('ukraine', 'Ukraine'),
    ('united arab emirates', 'United arab emirates'),
    ('united kingdom', 'United kingdom'),
    ('united states', 'United states'),
    ('uruguay', 'Uruguay'),
    ('uzbekistan', 'Uzbekistan'),
    ('vanuatu', 'Vanuatu'),
    ('vatican city', 'Vatican city'),
    ('venezuela', 'Venezuela'),
    ('vietnam', 'Vietnam'),
    ('yemen', 'Yemen'),
    ('zambia', 'Zambia'),
)

all_countries_with_phone_codes_choices_fields_format = (
    ('1', 'United States of America'),
    ('1', 'United States Virgin Islands'),
    ('1', 'Northern Mariana Islands'),
    ('1', 'Guam'),
    ('1', 'American Samoa'),
    ('1', 'Puerto Rico'),
    ('1', 'Canada'),
    ('1', 'Bahamas'),
    ('1', 'Barbados'),
    ('1', 'Anguilla'),
    ('1', 'Antigua and Barbuda'),
    ('1', 'British Virgin Islands'),
    ('1', 'Cayman Islands'),
    ('1', 'Bermuda'),
    ('1', 'Grenada'),
    ('1', 'Turks and Caicos Islands'),
    ('1', 'Jamaica'),
    ('1', 'Montserrat'),
    ('1', 'Sint Maarten'),
    ('1', 'Saint Lucia'),
    ('1', 'Dominica'),
    ('1', 'Saint Vincent and the Grenadines'),
    ('1', 'Dominican Republic'),
    ('1', 'Trinidad and Tobago'),
    ('1', 'Saint Kitts and Nevis'),
    ('20', 'Egypt'),
    ('211', 'South Sudan'),
    ('212', 'Morocco (including Western Sahara)'),
    ('213', 'Algeria'),
    ('216', 'Tunisia'),
    ('218', 'Libya'),
    ('220', 'Gambia'),
    ('221', 'Senegal'),
    ('222', 'Mauritania'),
    ('223', 'Mali'),
    ('224', 'Guinea'),
    ('225', 'Ivory Coast'),
    ('226', 'Burkina Faso'),
    ('227', 'Niger'),
    ('228', 'Togo'),
    ('229', 'Benin'),
    ('230', 'Mauritius'),
    ('231', 'Liberia'),
    ('232', 'Sierra Leone'),
    ('233', 'Ghana'),
    ('234', 'Nigeria'),
    ('235', 'Chad'),
    ('236', 'Central African Republic'),
    ('237', 'Cameroon'),
    ('238', 'Cape Verde'),
    ('239', 'São Tomé and Príncipe'),
    ('240', 'Equatorial Guinea'),
    ('241', 'Gabon'),
    ('242', 'Republic of the Congo'),
    ('243', 'Democratic Republic of the Congo'),
    ('244', 'Angola'),
    ('245', 'Guinea-Bissau'),
    ('246', 'British Indian Ocean Territory'),
    ('247', 'Ascension Island'),
    ('248', 'Seychelles'),
    ('249', 'Sudan'),
    ('250', 'Rwanda'),
    ('251', 'Ethiopia'),
    ('252', 'Somalia'),
    ('253', 'Djibouti'),
    ('254', 'Kenya'),
    ('255', 'Tanzania'),
    ('255', 'Zanzibar'),
    ('256', 'Uganda'),
    ('257', 'Burundi'),
    ('258', 'Mozambique'),
    ('260', 'Zambia'),
    ('261', 'Madagascar'),
    ('262', 'Réunion'),
    ('263', 'Zimbabwe'),
    ('264', 'Namibia'),
    ('265', 'Malawi'),
    ('266', 'Lesotho'),
    ('267', 'Botswana'),
    ('268', 'Eswatini'),
    ('269', 'Comoros'),
    ('27', 'South Africa'),
    ('290', 'Saint Helena'),
    ('290', 'Tristan da Cunha'),
    ('291', 'Eritrea'),
    ('297', 'Aruba'),
    ('298', 'Faroe Islands'),
    ('299', 'Greenland'),
    ('30', 'Greece'),
    ('31', 'Netherlands'),
    ('32', 'Belgium'),
    ('33', 'France'),
    ('34', 'Spain'),
    ('350', 'Gibraltar'),
    ('351', 'Portugal'),
    ('352', 'Luxembourg'),
    ('353', 'Ireland'),
    ('354', 'Iceland'),
    ('355', 'Albania'),
    ('356', 'Malta'),
    ('357', 'Cyprus'),
    ('358', 'Finland'),
    ('359', 'Bulgaria'),
    ('36', 'Hungary'),
    ('370', 'Lithuania'),
    ('371', 'Latvia'),
    ('372', 'Estonia'),
    ('373', 'Moldova'),
    ('374', 'Armenia'),
    ('374', 'Nagorno Karabakh'),
    ('375', 'Belarus'),
    ('376', 'Andorra'),
    ('377', 'Monaco'),
    ('378', 'San Marino'),
    ('379', 'Vatican City'),
    ('380', 'Ukraine'),
    ('381', 'Serbia'),
    ('382', 'Montenegro'),
    ('383', 'Kosovo'),
    ('385', 'Croatia'),
    ('386', 'Slovenia'),
    ('387', 'Bosnia and Herzegovina'),
    ('389', 'North Macedonia'),
    ('39', 'Italy'),
    ('39', 'San Marino'),
    ('39', 'Vatican City'),
    ('40', 'Romania'),
    ('41', 'Switzerland'),
    ('420', 'Czech Republic'),
    ('421', 'Slovakia'),
    ('43', 'Austria'),
    ('44', 'United Kingdom'),
    ('44', 'Guernsey'),
    ('44', 'Jersey'),
)

