# Generated by Django 4.2.2 on 2023-06-28 20:56

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Department',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('department_creation_date', models.DateTimeField(auto_now_add=True, verbose_name='Department creation date')),
                ('department_last_modified', models.DateTimeField(auto_now_add=True, verbose_name='Last modified on')),
                ('department_name', models.CharField(max_length=20, verbose_name='Department name')),
                ('department_email_address', models.EmailField(max_length=254, unique=True, verbose_name='Email address')),
                ('department_status', models.CharField(choices=[('Active', 'Active'), ('Inactive', 'Inactive'), ('N/A', 'N/A')], max_length=10, verbose_name='Department Status')),
            ],
        ),
    ]
