# Generated by Django 4.2.2 on 2023-06-28 21:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Projects', '0002_alter_project_project_name'),
        ('Departments', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='department',
            name='department_projects',
            field=models.ManyToManyField(to='Projects.project'),
        ),
    ]
