# Generated by Django 4.2.2 on 2023-06-28 22:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Departments', '0002_department_department_projects'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='department',
            name='department_projects',
        ),
    ]
